import "./security-shim.js";

/** Lumi DM V5 browser bridge.
 * Browser ownership is retained until Lumi persists a handoff. Downloads are
 * paused—not erased—while the desktop corner popup asks the user what to do.
 */
const DEFAULT_SERVER="http://localhost:7000",REQUEST_TTL=120000,CONTROL_TTL=30000,MAX_BODY=4*1024*1024;
let serverUrl=DEFAULT_SERVER,downloadDir="",interceptEnabled=true,hostModes={},repairPending=null;
const requests=new Map(),urls=new Map(),media=new Map(),forceTabs=new Map(),bypassTabs=new Map(),bypassUrls=new Map(),attachments=new Map(),armedTabs=new Map(),activeHandoffs=new Map(),recent=new Map();
const MEDIA_RE=/\.(m3u8|mpd|mp4|webm|mov|flv|ts|avi|mkv)(\?|#|$)/i;
const HLS_RE=/\.(m3u8|mpd)(\?|#|$)/i;
const SKIP=["data:","chrome://","chrome-extension://","moz-extension://"];
const DOWNLOAD_EXT=new Set(["zip","rar","7z","gz","tar","bz2","xz","zst","exe","msi","dmg","pkg","deb","rpm","apk","ipa","appx","mp4","mkv","avi","mov","wmv","flv","webm","ts","m2ts","mp3","flac","wav","aac","ogg","opus","m4a","pdf","epub","mobi","azw3","iso","img","bin","nrg","torrent","ipsw"]);
const WEB_EXT=new Set(["png","jpg","jpeg","gif","webp","svg","ico","bmp","avif","tiff","css","js","json","xml","html","htm","woff","woff2","ttf","eot","map"]);
const CAPTURE_HEADERS=new Set(["accept","accept-language","authorization","content-type","cookie","origin","proxy-authorization","referer","user-agent"]);

chrome.storage.local.get({server:DEFAULT_SERVER,downloadDir:"",interceptEnabled:true,hostModes:{}},value=>{serverUrl=normalise(value.server);downloadDir=value.downloadDir||"";interceptEnabled=value.interceptEnabled!==false;hostModes=value.hostModes||{};void refreshRepair()});
chrome.storage.onChanged.addListener(changes=>{if(changes.server)serverUrl=normalise(changes.server.newValue);if(changes.downloadDir)downloadDir=changes.downloadDir.newValue||"";if(changes.interceptEnabled)interceptEnabled=changes.interceptEnabled.newValue!==false;if(changes.hostModes)hostModes=changes.hostModes.newValue||{}});
chrome.alarms.create("LUMIDM-v5-keepalive",{periodInMinutes:.5});chrome.alarms.onAlarm.addListener(()=>{cleanup();void refreshRepair()});
function normalise(value){return String(value||DEFAULT_SERVER).replace(/\/$/,"")}
function localServer(){try{return["localhost","127.0.0.1","::1"].includes(new URL(serverUrl).hostname.toLowerCase())}catch{return false}}
function fetchTimeout(url,options={},timeout=8000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);return fetch(url,{...options,signal:controller.signal}).finally(()=>clearTimeout(timer))}
function cleanup(){const now=Date.now();for(const map of[forceTabs,bypassTabs,bypassUrls,attachments,armedTabs,recent])for(const[key,time]of map)if(now-Number(time||0)>REQUEST_TTL)map.delete(key);for(const[id,value]of requests)if(now-value.timestamp>REQUEST_TTL)requests.delete(id);for(const[url,value]of urls){const fresh=value.filter(item=>now-item.timestamp<=REQUEST_TTL);fresh.length?urls.set(url,fresh.slice(-6)):urls.delete(url)}}
function canonical(headers=[]){const result={};for(const header of headers){const lower=String(header.name||"").toLowerCase();if(!CAPTURE_HEADERS.has(lower)||header.value==null)continue;const name=lower.split("-").map(part=>part?part[0].toUpperCase()+part.slice(1):part).join("-");result[name]=String(header.value)}return result}
function bytes64(buffer){const bytes=new Uint8Array(buffer);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function bodyCapture(details){const body=details.requestBody;if(!body)return{body:null,error:""};const armed=repairPending||Date.now()-Number(armedTabs.get(details.tabId)||0)<CONTROL_TTL||localMode(details.url)==="always_lumi";if(!armed)return{body:null,error:""};if(body.formData){const encoded=JSON.stringify(body.formData);return encoded.length>MAX_BODY?{body:null,error:"POST form exceeds Lumi's 4 MB capture limit"}:{body:{kind:"form",data:body.formData},error:""}}let total=0,chunks=[];for(const item of body.raw||[]){if(!item.bytes)continue;total+=item.bytes.byteLength;if(total>MAX_BODY)return{body:null,error:"POST body exceeds Lumi's 4 MB capture limit"};chunks.push(bytes64(item.bytes))}return{body:chunks.length?{kind:"base64",data:chunks.join("")}:null,error:""}}
function remember(details){const current=requests.get(details.requestId)||{url:details.url,final_url:details.url,method:details.method||"GET",headers:{},post_body:null,capture_error:"",tabId:details.tabId,frameId:details.frameId,timestamp:Date.now()};current.final_url=details.url;current.method=details.method||current.method;current.tabId=details.tabId;current.timestamp=Date.now();const captured=bodyCapture(details);if(captured.body)current.post_body=captured.body;if(captured.error)current.capture_error=captured.error;requests.set(details.requestId,current);const bucket=urls.get(details.url)||[];bucket.push(current);urls.set(details.url,bucket.slice(-6));return current}
chrome.webRequest.onBeforeRequest.addListener(details=>{const current=remember(details);if(details.tabId>=0&&MEDIA_RE.test(details.url)){const list=media.get(details.tabId)||new Set();list.add(details.url);media.set(details.tabId,list);current.media=true}},{urls:["<all_urls>"]},["requestBody"]);
chrome.webRequest.onBeforeSendHeaders.addListener(details=>{const current=requests.get(details.requestId)||remember(details);current.headers={...current.headers,...canonical(details.requestHeaders)};current.timestamp=Date.now()},{urls:["<all_urls>"]},["requestHeaders","extraHeaders"]);
chrome.webRequest.onBeforeRedirect.addListener(details=>{const current=requests.get(details.requestId);if(!current)return;current.final_url=details.redirectUrl;current.timestamp=Date.now();const bucket=urls.get(details.redirectUrl)||[];bucket.push(current);urls.set(details.redirectUrl,bucket.slice(-6))},{urls:["<all_urls>"]});
chrome.webRequest.onHeadersReceived.addListener(details=>{const disposition=(details.responseHeaders||[]).find(header=>String(header.name).toLowerCase()==="content-disposition");if(disposition&&/attachment/i.test(disposition.value||""))attachments.set(details.url,Date.now())},{urls:["<all_urls>"]},["responseHeaders","extraHeaders"]);
chrome.webNavigation.onCommitted.addListener(details=>{if(details.frameId===0)media.delete(details.tabId)});chrome.tabs.onRemoved.addListener(id=>{media.delete(id);forceTabs.delete(id);bypassTabs.delete(id);armedTabs.delete(id)});
function capturedFor(url){const direct=urls.get(url)||[];if(direct.length)return direct[direct.length-1];const clean=String(url).split("#")[0];for(const[candidate,list]of urls)if(candidate.split("#")[0]===clean&&list.length)return list[list.length-1];return null}
async function cookies(url){try{return(await chrome.cookies.getAll({url})).map(item=>`${item.name}=${item.value}`).join("; ")}catch{return""}}
async function tabUrl(id){try{return(await chrome.tabs.get(id))?.url||""}catch{return""}}
async function envelope(url,item={},tab=null){const captured=capturedFor(item.finalUrl||url)||capturedFor(url)||{};const tabId=captured.tabId??tab?.id??-1;const headers={...(captured.headers||{})};if(!Object.keys(headers).some(name=>name.toLowerCase()==="cookie")){const value=await cookies(item.finalUrl||url);if(value)headers.Cookie=value}return{url:captured.url||url,final_url:item.finalUrl||captured.final_url||url,original_page:item.referrer||tab?.url||await tabUrl(tabId),method:captured.method||"GET",headers,...(captured.post_body?{post_body:captured.post_body}:{}),...(captured.capture_error?{capture_error:captured.capture_error}:{}),suggested_filename:fileName(item.filename||""),browser_profile:"chromium-mv3",captured_at:new Date().toISOString()}}
function fileName(value){return String(value||"").split(/[\\/]/).pop().trim()}
function extension(url){const clean=String(url||"").split(/[?#]/)[0],name=clean.split("/").pop()||"",dot=name.lastIndexOf(".");return dot>=0?name.slice(dot+1).toLowerCase():""}
function localMode(url){let host;try{host=new URL(url).hostname.toLowerCase()}catch{return"auto"}let best="auto",length=-1;for(const[pattern,mode]of Object.entries(hostModes||{})){const normal=String(pattern).toLowerCase().replace(/^\*\./,"");if((host===normal||host.endsWith(`.${normal}`))&&normal.length>length){best=mode;length=normal.length}}return best}
async function hostMode(url){const local=localMode(url);if(local!=="auto"||!localServer())return local;try{return(await(await fetchTimeout(`${serverUrl}/api/browser/intercept-mode?url=${encodeURIComponent(url)}`,{},1500)).json()).mode||"auto"}catch{return"auto"}}
function consume(map,key){const time=map.get(key);if(!time||Date.now()-time>CONTROL_TTL){map.delete(key);return false}map.delete(key);return true}
async function shouldIntercept(item,url,captured){if(!interceptEnabled||consume(bypassUrls,url))return false;const tabId=captured?.tabId??-1;if(consume(bypassTabs,tabId))return false;if(consume(forceTabs,tabId))return true;const mode=await hostMode(url);if(mode==="always_browser")return false;if(mode==="always_lumi")return true;const ext=extension(url);if(WEB_EXT.has(ext))return false;return attachments.has(url)||DOWNLOAD_EXT.has(ext)||(item.fileSize||0)>=2*1024*1024}
function duplicate(url){const now=Date.now(),last=recent.get(url);if(last&&now-last<5000)return true;recent.set(url,now);return false}
function pauseDownload(id){return new Promise((resolve,reject)=>chrome.downloads.pause(id,()=>chrome.runtime.lastError?reject(new Error(chrome.runtime.lastError.message)):resolve()))}
function resumeDownload(id){return new Promise(resolve=>chrome.downloads.resume(id,()=>resolve()))}
function cancelDownload(id){return new Promise(resolve=>chrome.downloads.cancel(id,()=>chrome.downloads.erase({id},()=>resolve())))}
async function ready(){if(!localServer())throw new Error("Lumi capture is restricted to the local server");const response=await fetchTimeout(`${serverUrl}/api/downloads?limit=1`,{},1800);if(!response.ok)throw new Error(`Lumi is not ready (${response.status})`);return true}
async function post(path,body){const response=await fetchTimeout(`${serverUrl}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function stage(url,type,filename,envelopeValue,browserId="",referrer=""){await ready();const detected=HLS_RE.test(url)?"video":type==="http"||type==="auto"?"auto":type;return post("/api/v5/browser/capture",{url,type:detected,filename,request_envelope:envelopeValue,browser_download_id:browserId,referrer,target_dir:downloadDir||undefined})}
async function monitorHandoff(handoffId,browserId,originalUrl){if(activeHandoffs.has(handoffId))return;activeHandoffs.set(handoffId,true);let failures=0;const deadline=Date.now()+11*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,900));try{const response=await fetchTimeout(`${serverUrl}/api/v5/browser/handoffs/${encodeURIComponent(handoffId)}`,{},2500);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();failures=0;if(data.decision==="pending")continue;if(data.decision==="lumi"||data.decision==="cancel"){if(browserId!==""&&browserId!=null)await cancelDownload(Number(browserId));notify(data.decision==="lumi"?"Lumi DM — Download started":"Lumi DM — Download cancelled",data.task?.filename||originalUrl);break}if(data.decision==="browser"){if(browserId!==""&&browserId!=null)await resumeDownload(Number(browserId));else chrome.downloads.download({url:originalUrl});notify("Lumi DM — Browser resumed",originalUrl);break}}catch(error){failures++;if(failures>=4){if(browserId!==""&&browserId!=null)await resumeDownload(Number(browserId));notify("Lumi DM — Browser resumed","Lumi became unavailable, so the browser kept the download.");break}}}activeHandoffs.delete(handoffId)}
async function refreshRepair(){if(!localServer()){repairPending=null;return null}try{repairPending=(await(await fetchTimeout(`${serverUrl}/api/browser/repair-pending`,{},1800)).json()).pending||null}catch{repairPending=null}return repairPending}
function repairMatches(pending,item,env){if(!pending)return false;const expectedName=String(pending.filename||"").toLowerCase().replace(/\s+/g,"");const actualName=String(fileName(item.filename||env.suggested_filename||"")).toLowerCase().replace(/\s+/g,"");if(expectedName&&actualName&&expectedName!==actualName&&!actualName.includes(expectedName)&&!expectedName.includes(actualName))return false;const expectedSize=Number(pending.expected_size||0),actualSize=Number(item.fileSize||0);if(expectedSize&&actualSize&&expectedSize!==actualSize)return false;return true}
async function repair(env){const response=await fetchTimeout(`${serverUrl}/api/browser/repair-capture`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request_envelope:env})});const data=await response.json();if(!response.ok||data.error)throw new Error(data.error||`HTTP ${response.status}`);repairPending=null;return data}
chrome.downloads.onCreated.addListener(item=>void handleCreated(item));
async function handleCreated(item){let url=item.finalUrl||item.url||"";if(!url||url.endsWith(".crx")||SKIP.some(prefix=>url.startsWith(prefix)))return;if(url.startsWith("blob:")){url=item.referrer||"";if(!url.startsWith("http"))return}const captured=capturedFor(url),pending=repairPending||await refreshRepair(),env=await envelope(url,item);if(pending&&repairMatches(pending,item,env)){if(env.capture_error)return notify("Lumi DM — Repair kept in browser",env.capture_error);try{await ready();const result=await repair(env);await cancelDownload(item.id);notify("Lumi DM — Link repaired",result.filename||pending.filename||url)}catch(error){notify("Lumi DM — Repair failed",error.message)}return}if(!(await shouldIntercept(item,url,captured))||duplicate(url))return;if(env.capture_error)return notify("Lumi DM — Browser kept download",env.capture_error);try{const type=url.startsWith("magnet:")||extension(url)==="torrent"?"torrent":HLS_RE.test(url)?"video":"auto";const result=await stage(url,type,fileName(item.filename),env,item.id,item.referrer||"");try{await pauseDownload(item.id)}catch{await post(`/api/v5/browser/handoffs/${encodeURIComponent(result.handoff.id)}/browser`,{}).catch(()=>{});return}notify("Lumi DM — Choose download options",result.task?.filename||url);void monitorHandoff(result.handoff.id,item.id,url)}catch(error){notify("Lumi DM — Browser kept download",error.message)}}
async function stageManual(url,type="auto",filename="",tab=null){armedTabs.set(tab?.id??-1,Date.now());const env=await envelope(url,{},tab);if(env.capture_error)throw new Error(env.capture_error);const result=await stage(url,HLS_RE.test(url)?"video":type,filename,env,"",tab?.url||"");notify("Lumi DM — Choose download options",result.task?.filename||url);void monitorHandoff(result.handoff.id,null,url);return result}
chrome.commands.onCommand.addListener(async command=>{const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)return;if(command==="lumi-force-next"){forceTabs.set(tab.id,Date.now());armedTabs.set(tab.id,Date.now());notify("Lumi DM","The next download in this tab will open Lumi's corner setup.")}else if(command==="lumi-bypass-next"){bypassTabs.set(tab.id,Date.now());notify("Lumi DM","The browser will handle the next download in this tab.")}});
chrome.runtime.onInstalled.addListener(()=>chrome.contextMenus.removeAll(()=>{for(const[id,title,contexts]of[["LUMIDM-download-link","Download with Lumi DM",["link"]],["LUMIDM-browser-link","Download with browser",["link"]],["LUMIDM-repair-link","Use link to repair Lumi download",["link"]],["LUMIDM-download-video","Download video with Lumi DM",["page","frame"]],["LUMIDM-grab-links","Grab all download links from this page",["page"]],["LUMIDM-host-always","Always use Lumi for this site",["page"]],["LUMIDM-host-browser","Always use browser for this site",["page"]],["LUMIDM-host-auto","Use automatic download rules for this site",["page"]]])chrome.contextMenus.create({id,title,contexts})}));
chrome.contextMenus.onClicked.addListener((info,tab)=>void(async()=>{try{if(info.menuItemId==="LUMIDM-download-link"&&info.linkUrl)return void await stageManual(info.linkUrl,"auto","",tab);if(info.menuItemId==="LUMIDM-browser-link"&&info.linkUrl){bypassUrls.set(info.linkUrl,Date.now());return void chrome.downloads.download({url:info.linkUrl})}if(info.menuItemId==="LUMIDM-repair-link"&&info.linkUrl){const result=await repair(await envelope(info.linkUrl,{},tab));return notify("Lumi DM — Link repaired",result.filename||info.linkUrl)}if(info.menuItemId==="LUMIDM-download-video"&&tab?.url)return void await stageManual(tab.url,"video","",tab);if(info.menuItemId==="LUMIDM-grab-links"&&tab?.id){await scanLinks(tab);return}if(["LUMIDM-host-always","LUMIDM-host-browser","LUMIDM-host-auto"].includes(info.menuItemId)){const mode=info.menuItemId==="LUMIDM-host-always"?"always_lumi":info.menuItemId==="LUMIDM-host-browser"?"always_browser":"auto";await setHost(tab?.url||info.pageUrl||"",mode)}}catch(error){notify("Lumi DM",error.message)}})());
async function setHost(url,mode){let host;try{host=new URL(url).hostname.toLowerCase()}catch{return}hostModes={...hostModes};if(mode==="auto")delete hostModes[host];else hostModes[host]=mode;await chrome.storage.local.set({hostModes});try{await post("/api/host-profiles",{id:`browser-${host.replace(/[^a-z0-9]+/g,"-")}`,name:`Browser rule for ${host}`,host_pattern:host,intercept_mode:mode,enabled:mode!=="auto"})}catch{}notify("Lumi DM",mode==="auto"?`Automatic rules restored for ${host}`:`Rule saved for ${host}`)}
async function scanLinks(tab){try{const result=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>[...document.querySelectorAll("a[href]")].map(a=>({url:a.href,filename:a.textContent.trim()})).filter(item=>/^https?:/.test(item.url))});await chrome.storage.local.set({grabResults:{url:tab.url,links:result?.[0]?.result||[],ts:Date.now()}});await chrome.action.openPopup()}catch{chrome.tabs.create({url:`${serverUrl}/?grab=${encodeURIComponent(tab.url)}`})}}
chrome.webNavigation.onBeforeNavigate.addListener(details=>void(async()=>{if(details.frameId!==0||!interceptEnabled)return;const url=details.url||"";if(!url.startsWith("magnet:")&&extension(url)!=="torrent")return;try{await stageManual(url,"torrent","",await chrome.tabs.get(details.tabId));chrome.tabs.remove(details.tabId)}catch(error){notify("Lumi DM — Browser kept link",error.message)}})());
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message.type==="DOWNLOAD"){void stageManual(message.url,message.dlType||"auto",message.filename||"",sender.tab||null).then(result=>sendResponse({ok:true,result})).catch(error=>sendResponse({ok:false,result:{error:error.message}}));return true}if(message.type==="GET_SNIFFED_MEDIA"){const id=message.tabId??sender.tab?.id??-1;sendResponse({ok:true,urls:id>=0?[...(media.get(id)||[])]:[]});return false}if(message.type==="GET_VIDEO_FORMATS"){fetchTimeout(`${serverUrl}/api/downloads/video/formats?url=${encodeURIComponent(message.url)}`).then(r=>r.json()).then(data=>sendResponse({ok:true,data})).catch(error=>sendResponse({ok:false,error:error.message}));return true}if(message.type==="GET_STATUS"){fetchTimeout(`${serverUrl}/api/downloads?limit=20`).then(r=>r.json()).then(data=>sendResponse({ok:true,data})).catch(error=>sendResponse({ok:false,error:error.message}));return true}if(message.type==="GET_REPAIR_PENDING"){void refreshRepair().then(pending=>sendResponse({ok:true,pending}));return true}if(message.type==="OPEN_DESKTOP"){void post("/api/v5/desktop/command",{action:"show-main"}).then(result=>sendResponse({ok:true,result})).catch(error=>sendResponse({ok:false,error:error.message}));return true}if(message.type==="SET_SERVER"){serverUrl=normalise(message.server);chrome.storage.local.set({server:serverUrl});sendResponse({ok:true,localOnly:localServer()});return false}if(message.type==="SET_DIR"){downloadDir=message.dir||"";chrome.storage.local.set({downloadDir});sendResponse({ok:true});return false}if(message.type==="SET_INTERCEPT"){interceptEnabled=message.enabled!==false;chrome.storage.local.set({interceptEnabled});sendResponse({ok:true});return false}return false});
function notify(title,message){chrome.notifications.create({type:"basic",iconUrl:"icons/icon48.png",title,message:String(message||"").slice(0,240)})}
